# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Tests for the instance://metadata MCP resource.

Regression guard: the resource must register every metric calculator the
``InstanceInfo`` schema requires.  A missing calculator (historically
``feature_availability``) made ``_generate_instance_info`` raise a
pydantic ValidationError, and the resource silently degraded to its
error payload instead of returning metadata.
"""

from unittest.mock import MagicMock, Mock, patch

import pytest

from superset.mcp_service.system.schemas import InstanceInfo
from superset.mcp_service.system.system_utils import (
    calculate_dashboard_breakdown,
    calculate_database_breakdown,
    calculate_feature_availability,
    calculate_instance_summary,
    calculate_popular_content,
    calculate_recent_activity,
)
from superset.utils import json

REQUIRED_METRICS = {
    "instance_summary": calculate_instance_summary,
    "recent_activity": calculate_recent_activity,
    "dashboard_breakdown": calculate_dashboard_breakdown,
    "database_breakdown": calculate_database_breakdown,
    "popular_content": calculate_popular_content,
    "feature_availability": calculate_feature_availability,
}


@pytest.fixture(autouse=True)
def mock_auth():
    """Mock authentication for all tests (mirrors test_get_current_user)."""
    with patch("superset.mcp_service.auth.get_user_from_request") as mock_get_user:
        mock_user = Mock()
        mock_user.id = 1
        mock_user.username = "admin"
        mock_user.roles = []
        mock_get_user.return_value = mock_user
        yield mock_get_user


def _required_metric_names() -> set[str]:
    """Metric names required by the InstanceInfo output schema."""
    # timestamp is generated by the core itself and current_user is
    # optional (default None, filled by the tool layer from g.user), so
    # neither needs a calculator wired in the resource.
    return set(InstanceInfo.model_fields.keys()) - {"timestamp", "current_user"}


def test_resource_registers_every_required_metric_calculator():
    """Every schema-required metric has a calculator wired in the resource."""
    from superset.mcp_service.system.resources import instance_metadata

    captured: dict = {}
    empty_info = json.dumps({})

    def _capturing_core(**kwargs):
        captured.update(kwargs)
        core = MagicMock()
        # Minimal DAO access used by the resource after construction
        core.dao_classes = {"datasets": MagicMock(), "databases": MagicMock()}
        core.dao_classes["datasets"].find_all.return_value = []
        core.dao_classes["databases"].find_all.return_value = []
        core.get_resource.return_value = empty_info
        return core

    with patch(
        "superset.mcp_service.mcp_core.InstanceInfoCore", side_effect=_capturing_core
    ):
        result = instance_metadata.get_instance_metadata_resource()

    assert set(captured["metric_calculators"].keys()) == _required_metric_names()
    assert captured["metric_calculators"] == REQUIRED_METRICS
    # The resource returned real metadata, not its error payload
    assert json.loads(result) != {}


def test_every_required_metric_has_a_calculator():
    """The known set of calculators covers every schema-required metric."""
    assert set(REQUIRED_METRICS.keys()) == _required_metric_names()
