# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# Build from the repository root. Frontend assets come from the matching release.
ARG SUPERSET_BASE_IMAGE=apache/superset:6.1.0@sha256:16b50bbef6648912a79e3293d418fefa743ce555d36c5af6b85d859119ed7f88
FROM ${SUPERSET_BASE_IMAGE}
USER root
WORKDIR /app
COPY superset/ /app/superset/
COPY superset-core/ /app/superset-core/
COPY pyproject.toml setup.py MANIFEST.in /app/
RUN uv pip install -e '.[postgres,fastmcp]' \
      'fastmcp==3.4.7' 'clickhouse-connect==1.8.0' \
      'shillelagh[genericjsonapi,s3selectapi]==1.4.3' \
    && uv pip check
ARG VCS_REF=unknown
LABEL org.opencontainers.image.revision=${VCS_REF}
USER superset
